import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Footer } from '../components/Footer'
import { TypingContainer } from '../components/TypingContainer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Typing Trainer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="#">Typing Trainer!</a>
                </h1>

                <p className={styles.description}>
                    Get started by focusing the input
                </p>

                <div className={styles.grid}>
                    <TypingContainer />
                </div>
            </main>

            <Footer />
        </div>
    )
}

export default Home
